-- Supabase の SQL Editor でこのファイルの内容をそのまま実行してください。
-- 多摩キャン版（/tama/）のコミュニティを作り直します（2026-10-07、あおの依頼「オーナー制度・公開範囲と参加条件・消せるように・必要な機能」）。
-- 触るのは tama_rooms / tama_room_members / tama_room_messages と、このファイルで作る表・関数だけ（通常版・学園祭版には触らない）。
-- 何度実行しても同じ結果になるように書いてあります（再実行しても壊れません）。
-- 実行しなくてもアプリは今まで通り動く（コミュニティが前のしくみのまま＝だれでも入れる・消せない）。
--
-- 変わること
--   ・作った人がオーナー（👑）。部屋の編集・投稿の削除・メンバーに退出してもらう（再参加を止める）・オーナーを譲る・部屋を閉じる（消す）ができる
--   ・だれが入れるか：'all'（だれでも）/ 'common'（共通点のある人だけ。一覧にも当てはまる人にしか出ない）/ 'invite'（招待コードを知っている人だけ）
--   ・期限（既定はアプリで2週間）。期限が来たら読むだけになり、3日後に消える。定員。ルール。集まる約束（いつ・どこで・行く人）
--   ・投稿を読めるのは参加している人だけ。参加・作成・編集はここの関数からだけ（アプリから表を直接書き換えられない）
--   ・1人が同時に持てる部屋は3つまで
-- ⚠️ 部屋の id の型（uuid / bigint）はダッシュボードで作られていて記録が無いので、くらべる所はすべて ::text にしている

-- ---------------------------------------------------------------------------
-- 1. 列と表を足す
-- ---------------------------------------------------------------------------
alter table public.tama_rooms add column if not exists owner_id   uuid;
alter table public.tama_rooms add column if not exists rules      text  not null default '';
alter table public.tama_rooms add column if not exists visibility text  not null default 'all';
alter table public.tama_rooms add column if not exists conditions jsonb not null default '[]'::jsonb;   -- [{k:'aru', v:'方向音痴', label:'わかる「方向音痴」'}, ...] どれか1つに当てはまればよい
alter table public.tama_rooms add column if not exists capacity   int;                                 -- 定員（null＝なし）
alter table public.tama_rooms add column if not exists expires_at timestamptz;                         -- 期限（null＝なし）
alter table public.tama_rooms add column if not exists meet       jsonb;                               -- 集まる約束 {when, place, note}
alter table public.tama_rooms add column if not exists updated_at timestamptz not null default now();
alter table public.tama_room_members  add column if not exists muted boolean not null default false;    -- この部屋の通知をオフ
-- 投稿を1つずつ消すために id が要る（ダッシュボードで作った表には普通もうある。無ければ足す）
alter table public.tama_room_messages add column if not exists id bigint generated by default as identity;

-- 退出してもらった人（再参加できない）・招待コード・集まる約束に行く人。読み書きは下の関数からだけ（ポリシーを作らない）
create table if not exists public.tama_room_bans (
  room_id    text        not null,
  user_id    uuid        not null,
  created_at timestamptz not null default now(),
  primary key (room_id, user_id)
);
create table if not exists public.tama_room_codes (
  room_id text primary key,
  code    text not null unique
);
create table if not exists public.tama_room_rsvp (
  room_id    text        not null,
  user_id    uuid        not null,
  created_at timestamptz not null default now(),
  primary key (room_id, user_id)
);
alter table public.tama_room_bans  enable row level security;
alter table public.tama_room_codes enable row level security;
alter table public.tama_room_rsvp  enable row level security;

-- ---------------------------------------------------------------------------
-- 2. 判定に使う関数
-- ---------------------------------------------------------------------------
-- 参加しているか・オーナーか（RLS の中から呼んでも、表を読み直して無限ループにならないよう security definer）
create or replace function public.tama_room_is_member(p_room text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.tama_room_members m where m.room_id::text = p_room and m.user_id = auth.uid());
$$;
create or replace function public.tama_room_is_owner(p_room text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.tama_rooms r where r.id::text = p_room and r.owner_id = auth.uid());
$$;

-- アーティスト名をそろえる（アプリの normAns とほぼ同じ。ひらがな・カタカナの違いだけはそろえない）
create or replace function public.tama_norm(s text)
returns text language sql immutable as $$
  select lower(regexp_replace(normalize(coalesce(s, ''), NFKC), '[[:space:]・,.、。!?！？''"「」『』()（）ー-]', '', 'g'));
$$;

-- 参加条件に当てはまるか（条件が空なら true）。fa はその人の tama_profiles.fes_attrs
create or replace function public.tama_room_fits(p_cond jsonb, p_fa jsonb)
returns boolean language sql immutable as $$
  select coalesce(jsonb_array_length(p_cond), 0) = 0 or exists (
    select 1 from jsonb_array_elements(p_cond) c
     where (c->>'k' = 'aru'   and coalesce(p_fa->'aruaru',   '[]'::jsonb) ? (c->>'v'))
        or (c->>'k' = 'pur'   and coalesce(p_fa->'purposes', '[]'::jsonb) ? (c->>'v'))
        or (c->>'k' = 'goal'  and coalesce(p_fa->'goals',    '[]'::jsonb) ? (c->>'v'))
        or (c->>'k' = 'fac'   and p_fa->>'faculty' = c->>'v')
        or (c->>'k' = 'grade' and p_fa->>'grade'   = c->>'v')
        or (c->>'k' = 'art'   and public.tama_norm(p_fa->>'artist') <> '' and public.tama_norm(p_fa->>'artist') = public.tama_norm(c->>'v'))
  );
$$;

create or replace function public.tama_my_fa()
returns jsonb language sql stable security definer set search_path = public as $$
  select coalesce((select p.fes_attrs from public.tama_profiles p where p.id::text = auth.uid()::text), '{}'::jsonb);
$$;

-- ---------------------------------------------------------------------------
-- 3. 一覧（自分に見える部屋だけ。人数・未読・当てはまるか・行く人の数つき）
-- ---------------------------------------------------------------------------
-- 見える部屋：参加している部屋（終わった部屋も）＋ 期限内で、招待制でなく、だれでも or 自分が当てはまる部屋
drop function if exists public.tama_room_list();
create or replace function public.tama_room_list()
returns table (id text, name text, topic text, rules text, visibility text, conditions jsonb, capacity int,
               expires_at timestamptz, meet jsonb, owner_id uuid, owner_name text, owner_emoji text, created_at timestamptz,
               members int, last_at timestamptz, joined boolean, muted boolean, unread int, fits boolean, going int, i_going boolean)
language sql stable security definer set search_path = public as $$
  with me as (select auth.uid() as uid, public.tama_my_fa() as fa)
  select r.id::text, r.name, coalesce(r.topic, ''), r.rules, r.visibility, r.conditions, r.capacity,
         r.expires_at, r.meet, r.owner_id, op.name, op.emoji, r.created_at,
         (select count(*)::int from public.tama_room_members m where m.room_id::text = r.id::text),
         (select max(x.created_at) from public.tama_room_messages x where x.room_id::text = r.id::text),
         mm.user_id is not null,
         coalesce(mm.muted, false),
         case when mm.user_id is null then 0
              else (select count(*)::int from public.tama_room_messages x
                     where x.room_id::text = r.id::text and x.from_id::text <> me.uid::text and x.created_at > mm.last_read_at) end,
         public.tama_room_fits(r.conditions, me.fa),
         (select count(*)::int from public.tama_room_rsvp v where v.room_id = r.id::text),
         exists (select 1 from public.tama_room_rsvp v where v.room_id = r.id::text and v.user_id = me.uid)
    from public.tama_rooms r
    cross join me
    left join public.tama_profiles op on op.id::text = r.owner_id::text
    left join public.tama_room_members mm on mm.room_id::text = r.id::text and mm.user_id = me.uid
   where me.uid is not null
     and (mm.user_id is not null
          or ((r.expires_at is null or r.expires_at > now())
              and r.visibility <> 'invite'
              and (r.visibility = 'all' or r.owner_id = me.uid or public.tama_room_fits(r.conditions, me.fa))))
   order by r.created_at desc;
$$;

-- ---------------------------------------------------------------------------
-- 4. 作る・参加する・招待コードで入る
-- ---------------------------------------------------------------------------
drop function if exists public.tama_room_create(text, text, text, text, jsonb, int, int, jsonb);
create or replace function public.tama_room_create(p_name text, p_topic text, p_rules text, p_visibility text,
                                                   p_conditions jsonb, p_capacity int, p_days int, p_meet jsonb)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  me     uuid := auth.uid();
  v_room text;
  v_code text;
  v_vis  text := case when p_visibility in ('all', 'common', 'invite') then p_visibility else 'all' end;
begin
  if me is null then raise exception 'not signed in'; end if;
  if coalesce(trim(p_name), '') = '' then return jsonb_build_object('status', 'name'); end if;
  if v_vis = 'common' and coalesce(jsonb_array_length(p_conditions), 0) = 0 then return jsonb_build_object('status', 'cond'); end if;
  if (select count(*) from public.tama_rooms where owner_id = me and (expires_at is null or expires_at > now())) >= 3 then
    return jsonb_build_object('status', 'too_many');
  end if;
  insert into public.tama_rooms (name, topic, rules, visibility, conditions, capacity, expires_at, meet, owner_id)
  values (left(trim(p_name), 20), left(coalesce(p_topic, ''), 40), left(coalesce(p_rules, ''), 300), v_vis,
          case when v_vis = 'common' then p_conditions else '[]'::jsonb end,
          case when p_capacity between 2 and 200 then p_capacity end,
          case when p_days between 1 and 60 then now() + make_interval(days => p_days) end,
          p_meet, me)
  returning id::text into v_room;
  insert into public.tama_room_members (room_id, user_id, last_read_at)
  select r.id, me, now() from public.tama_rooms r where r.id::text = v_room;
  if v_vis = 'invite' then
    loop
      v_code := upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));
      exit when not exists (select 1 from public.tama_room_codes c where c.code = v_code);
    end loop;
    insert into public.tama_room_codes (room_id, code) values (v_room, v_code);
  end if;
  return jsonb_build_object('status', 'ok', 'room', v_room, 'code', v_code);
end $$;

-- 返り値：'ok' / 'gone'（部屋が無い）/ 'ended'（期限切れ）/ 'banned'（退出してもらった）/ 'code'（招待コードが違う）/ 'unfit'（条件に当てはまらない）/ 'full'（定員）
drop function if exists public.tama_room_join(text, text);
create or replace function public.tama_room_join(p_room text, p_code text default null)
returns text language plpgsql volatile security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  r  public.tama_rooms%rowtype;
begin
  if me is null then raise exception 'not signed in'; end if;
  select * into r from public.tama_rooms where id::text = p_room;
  if not found then return 'gone'; end if;
  if exists (select 1 from public.tama_room_members m where m.room_id::text = p_room and m.user_id = me) then return 'ok'; end if;
  if r.expires_at is not null and r.expires_at <= now() then return 'ended'; end if;
  if exists (select 1 from public.tama_room_bans b where b.room_id = p_room and b.user_id = me) then return 'banned'; end if;
  if r.owner_id is distinct from me then
    if r.visibility = 'invite' and not exists (select 1 from public.tama_room_codes c where c.room_id = p_room and c.code = upper(trim(coalesce(p_code, '')))) then
      return 'code';
    end if;
    if r.visibility = 'common' and not public.tama_room_fits(r.conditions, public.tama_my_fa()) then return 'unfit'; end if;
  end if;
  if r.capacity is not null and (select count(*) from public.tama_room_members m where m.room_id::text = p_room) >= r.capacity then
    return 'full';
  end if;
  insert into public.tama_room_members (room_id, user_id, last_read_at) values (r.id, me, now());
  return 'ok';
end $$;

-- 招待コードで入る。{status, room}
drop function if exists public.tama_room_join_code(text);
create or replace function public.tama_room_join_code(p_code text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare v_room text;
begin
  select c.room_id into v_room from public.tama_room_codes c where c.code = upper(trim(coalesce(p_code, '')));
  if v_room is null then return jsonb_build_object('status', 'code'); end if;
  return jsonb_build_object('status', public.tama_room_join(v_room, p_code), 'room', v_room);
end $$;

-- ---------------------------------------------------------------------------
-- 5. オーナーができること
-- ---------------------------------------------------------------------------
-- 編集。p_days：null＝期限を変えない / 0＝期限なし / 1〜60＝今から◯日
drop function if exists public.tama_room_update(text, text, text, text, text, jsonb, int, int, jsonb);
create or replace function public.tama_room_update(p_room text, p_name text, p_topic text, p_rules text, p_visibility text,
                                                   p_conditions jsonb, p_capacity int, p_days int, p_meet jsonb)
returns text language plpgsql volatile security definer set search_path = public as $$
declare
  v_vis  text := case when p_visibility in ('all', 'common', 'invite') then p_visibility else 'all' end;
  v_code text;
begin
  if not public.tama_room_is_owner(p_room) then return 'not_owner'; end if;
  if coalesce(trim(p_name), '') = '' then return 'name'; end if;
  if v_vis = 'common' and coalesce(jsonb_array_length(p_conditions), 0) = 0 then return 'cond'; end if;
  update public.tama_rooms set
    name = left(trim(p_name), 20), topic = left(coalesce(p_topic, ''), 40), rules = left(coalesce(p_rules, ''), 300),
    visibility = v_vis, conditions = case when v_vis = 'common' then p_conditions else '[]'::jsonb end,
    capacity = case when p_capacity between 2 and 200 then p_capacity end,
    expires_at = case when p_days is null then expires_at when p_days between 1 and 60 then now() + make_interval(days => p_days) else null end,
    meet = p_meet, updated_at = now()
  where id::text = p_room;
  if v_vis = 'invite' and not exists (select 1 from public.tama_room_codes c where c.room_id = p_room) then
    loop
      v_code := upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));
      exit when not exists (select 1 from public.tama_room_codes c where c.code = v_code);
    end loop;
    insert into public.tama_room_codes (room_id, code) values (p_room, v_code);
  end if;
  return 'ok';
end $$;

-- 招待コードを見る（オーナーだけ）
drop function if exists public.tama_room_code(text);
create or replace function public.tama_room_code(p_room text)
returns text language sql stable security definer set search_path = public as $$
  select c.code from public.tama_room_codes c where c.room_id = p_room and public.tama_room_is_owner(p_room);
$$;

-- メンバーに退出してもらう（p_ban＝再参加できないようにする）
drop function if exists public.tama_room_kick(text, uuid, boolean);
create or replace function public.tama_room_kick(p_room text, p_user uuid, p_ban boolean default true)
returns text language plpgsql volatile security definer set search_path = public as $$
begin
  if not public.tama_room_is_owner(p_room) then return 'not_owner'; end if;
  if p_user = auth.uid() then return 'self'; end if;
  delete from public.tama_room_members where room_id::text = p_room and user_id = p_user;
  delete from public.tama_room_rsvp where room_id = p_room and user_id = p_user;
  if p_ban then insert into public.tama_room_bans (room_id, user_id) values (p_room, p_user) on conflict do nothing; end if;
  return 'ok';
end $$;

-- 投稿を消す（書いた本人か、その部屋のオーナー）
drop function if exists public.tama_room_delete_msg(text);
create or replace function public.tama_room_delete_msg(p_msg text)
returns text language plpgsql volatile security definer set search_path = public as $$
declare v_room text; v_from text;
begin
  select x.room_id::text, x.from_id::text into v_room, v_from from public.tama_room_messages x where x.id::text = p_msg;
  if v_room is null then return 'gone'; end if;
  if v_from <> auth.uid()::text and not public.tama_room_is_owner(v_room) then return 'denied'; end if;
  delete from public.tama_room_messages where id::text = p_msg;
  return 'ok';
end $$;

-- オーナーを譲る（相手は参加している人）
drop function if exists public.tama_room_transfer(text, uuid);
create or replace function public.tama_room_transfer(p_room text, p_user uuid)
returns text language plpgsql volatile security definer set search_path = public as $$
begin
  if not public.tama_room_is_owner(p_room) then return 'not_owner'; end if;
  if not exists (select 1 from public.tama_room_members m where m.room_id::text = p_room and m.user_id = p_user) then return 'not_member'; end if;
  update public.tama_rooms set owner_id = p_user, updated_at = now() where id::text = p_room;
  return 'ok';
end $$;

-- 部屋を閉じる＝消す（投稿・参加者・招待コード・行く人もまとめて。元に戻せない）
create or replace function public.tama_room_purge(p_room text)
returns void language sql volatile security definer set search_path = public as $$
  delete from public.tama_room_messages where room_id::text = p_room;
  delete from public.tama_room_members  where room_id::text = p_room;
  delete from public.tama_room_bans     where room_id = p_room;
  delete from public.tama_room_codes    where room_id = p_room;
  delete from public.tama_room_rsvp     where room_id = p_room;
  delete from public.tama_rooms         where id::text = p_room;
$$;
drop function if exists public.tama_room_close(text);
create or replace function public.tama_room_close(p_room text)
returns text language plpgsql volatile security definer set search_path = public as $$
begin
  if not public.tama_room_is_owner(p_room) then return 'not_owner'; end if;
  perform public.tama_room_purge(p_room);
  return 'ok';
end $$;

-- ---------------------------------------------------------------------------
-- 6. 参加している人ができること・片づけ
-- ---------------------------------------------------------------------------
-- 集まる約束に「行く」（参加している人だけ）
drop function if exists public.tama_room_rsvp_set(text, boolean);
create or replace function public.tama_room_rsvp_set(p_room text, p_going boolean)
returns text language plpgsql volatile security definer set search_path = public as $$
begin
  if not public.tama_room_is_member(p_room) then return 'not_member'; end if;
  if p_going then insert into public.tama_room_rsvp (room_id, user_id) values (p_room, auth.uid()) on conflict do nothing;
  else delete from public.tama_room_rsvp where room_id = p_room and user_id = auth.uid(); end if;
  return 'ok';
end $$;

-- 「プロフィールを消す」の前に呼ぶ：自分がオーナーの部屋は、いちばん前から参加している人に譲る（だれもいなければ消す）
drop function if exists public.tama_room_forget_me();
create or replace function public.tama_room_forget_me()
returns void language plpgsql volatile security definer set search_path = public as $$
declare r record; v_next uuid;
begin
  for r in select id::text as id from public.tama_rooms where owner_id = auth.uid() loop
    select m.user_id into v_next from public.tama_room_members m
     where m.room_id::text = r.id and m.user_id <> auth.uid() order by m.joined_at limit 1;
    if v_next is null then perform public.tama_room_purge(r.id);
    else update public.tama_rooms set owner_id = v_next, updated_at = now() where id::text = r.id; end if;
  end loop;
  delete from public.tama_room_rsvp where user_id = auth.uid();
end $$;

-- 期限から3日たった部屋を消す（アプリが一覧を読む時に、1時間に1回まで呼ぶ）
drop function if exists public.tama_room_cleanup();
create or replace function public.tama_room_cleanup()
returns int language plpgsql volatile security definer set search_path = public as $$
declare r record; n int := 0;
begin
  for r in select id::text as id from public.tama_rooms where expires_at < now() - interval '3 days' loop
    perform public.tama_room_purge(r.id); n := n + 1;
  end loop;
  return n;
end $$;

revoke all on function public.tama_room_is_member(text), public.tama_room_is_owner(text), public.tama_my_fa(),
                       public.tama_room_list(), public.tama_room_create(text, text, text, text, jsonb, int, int, jsonb),
                       public.tama_room_join(text, text), public.tama_room_join_code(text),
                       public.tama_room_update(text, text, text, text, text, jsonb, int, int, jsonb), public.tama_room_code(text),
                       public.tama_room_kick(text, uuid, boolean), public.tama_room_delete_msg(text), public.tama_room_transfer(text, uuid),
                       public.tama_room_purge(text), public.tama_room_close(text), public.tama_room_rsvp_set(text, boolean),
                       public.tama_room_forget_me(), public.tama_room_cleanup()
  from public, anon;
grant execute on function public.tama_room_is_member(text), public.tama_room_is_owner(text), public.tama_my_fa(),
                          public.tama_room_list(), public.tama_room_create(text, text, text, text, jsonb, int, int, jsonb),
                          public.tama_room_join(text, text), public.tama_room_join_code(text),
                          public.tama_room_update(text, text, text, text, text, jsonb, int, int, jsonb), public.tama_room_code(text),
                          public.tama_room_kick(text, uuid, boolean), public.tama_room_delete_msg(text), public.tama_room_transfer(text, uuid),
                          public.tama_room_close(text), public.tama_room_rsvp_set(text, boolean),
                          public.tama_room_forget_me(), public.tama_room_cleanup()
  to authenticated;
-- tama_room_purge は関数の中からだけ使う（だれにも直接は呼ばせない）

-- ---------------------------------------------------------------------------
-- 7. RLS を作り直す（前のポリシーはダッシュボードで作られた名前が分からないので、3つの表の分を全部消してから作る）
-- ---------------------------------------------------------------------------
do $$
declare p record;
begin
  for p in select policyname, tablename from pg_policies
            where schemaname = 'public' and tablename in ('tama_rooms', 'tama_room_members', 'tama_room_messages') loop
    execute format('drop policy %I on public.%I', p.policyname, p.tablename);
  end loop;
end $$;
alter table public.tama_rooms         enable row level security;
alter table public.tama_room_members  enable row level security;
alter table public.tama_room_messages enable row level security;

-- 部屋の情報（名前・ルールなど）はだれでも読める。作る・変える・消すは関数から（ポリシーを作らない）。招待コードは別の表
create policy "read rooms" on public.tama_rooms for select to authenticated using (true);

-- だれが入っているかは、同じ部屋の人だけ読める（悩みの部屋などで、参加していることが外に分からないように）
create policy "members read members" on public.tama_room_members for select to authenticated
  using (user_id = auth.uid() or public.tama_room_is_member(room_id::text));
-- 既読の時刻と通知のオフだけ自分で変えられる（参加は関数から。部屋を書き換えて入れないよう、列も絞る）
create policy "update own membership" on public.tama_room_members for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
revoke update on public.tama_room_members from authenticated;
grant update (last_read_at, muted) on public.tama_room_members to authenticated;
create policy "leave as self" on public.tama_room_members for delete to authenticated
  using (user_id = auth.uid());

-- 投稿は参加している人だけ読める・書ける（消すのは関数から）
create policy "members read messages" on public.tama_room_messages for select to authenticated
  using (public.tama_room_is_member(room_id::text));
create policy "members post" on public.tama_room_messages for insert to authenticated
  with check (from_id::text = auth.uid()::text and public.tama_room_is_member(room_id::text));

notify pgrst, 'reload schema';

-- 確認：1つめは関数が14行、2つめはポリシーが tama_room_members=3・tama_room_messages=2・tama_rooms=1
select proname from pg_proc
 where proname in ('tama_room_list', 'tama_room_create', 'tama_room_join', 'tama_room_join_code', 'tama_room_update', 'tama_room_code',
                   'tama_room_kick', 'tama_room_delete_msg', 'tama_room_transfer', 'tama_room_close', 'tama_room_rsvp_set',
                   'tama_room_forget_me', 'tama_room_cleanup', 'tama_room_fits')
 order by proname;
select tablename, count(*) as ポリシー数 from pg_policies
 where schemaname = 'public' and tablename in ('tama_rooms', 'tama_room_members', 'tama_room_messages')
 group by tablename order by tablename;
